### PR TITLE
CI Workflow for Aether

### PR DESCRIPTION
**Pull request by eXhumer**
[Build Status](https://travis-ci.com/eXhumer/Aether)

Travis CI and GitHub Actions CI Workflow properly implemented on my repo.

Any new merge will auto create, push and deploy the documentations, thanks to GitHub Actions.

| KEY                     | VALUE                 |
|:-----------------------:|:---------------------:|
| `REPO_USERNAME`         | `<your-git-username>` |
| `REPO_EMAIL`            | `<your-git-email`     |
| `PERSONAL_ACCESS_TOKEN` | `<your-access-token>` |

Add all the the listed variables to your GitHub repository from [here](https://github.com/tallbl0nde/Aether/settings/secrets) to properly configure push with GitHub Actions.

Both Travis CI & GitHub Actions are responsible for build testing. Only GitHub Actions is responsible for pushing new documentations currently. (Travis CI also has the steps to push also, but commented out as it is best to have only one build system try to push changes at a time)

If you have any further question, let me know.

### CODE REVIEW

**Comment by eXhumer** [comment]
9fd01eb is a docs commit generated and pushed by GitHub Actions.

**Comment by eXhumer** [comment]
[Travis CI - Library Build Test](https://travis-ci.com/github/eXhumer/Aether/builds/169999840) for commit a30b8e9, 796c9e5 & ae77284.
[Travis CI - Library Build Test](https://travis-ci.com/github/eXhumer/Aether/builds/170009792) for commit 9fd01eb (auto docs push by GitHub Actions Workflow).

[GitHub Actions Workflow - Library Build Test](https://github.com/eXhumer/Aether/runs/744135238) for commit a30b8e9, 796c9e5 & ae77284.
[GitHub Actions Workflow - Library Documentation Generation & Deploy](https://github.com/eXhumer/Aether/runs/744135265) for commit a30b8e9, 796c9e5 & ae77284.

**Comment by eXhumer** [comment]
Force-pushes were done to overwrite all the small commits I made for various bugfixes into one commit. :P

**Comment by tallbl0nde** [comment]
Thanks a heap! You're making this feel like a proper library :P

Is this all good to merge now?

**Comment by tallbl0nde** [comment]
Also where do I get my access token from? Is it something I need to generate and set elsewhere too?

**Comment by eXhumer** [comment]
Refer to [this](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line) for creating personal access token. You will need to create a token with scope `public_repo` only.

**Comment by eXhumer** [comment]
And it is all ready to merge as is, as long as you have added the secret variables I mentioned in the first comment and have enabled activated Travis CI for this repository from your Travis CI account.

**Comment by eXhumer** [comment]
https://github.com/eXhumer/Aether#for-arch-linux-based-distro--windows-users
https://github.com/eXhumer/Aether#for-all-others-unix-based-distro-users

If you have question about why these steps are needed, it is to include the switch variant of `sdl2-config` & `freetype-config` before any other config.

**Comment by tallbl0nde** [comment]
Alright I believe it's all setup! Let's see how it goes...

**Pull request merged**
