### PR TITLE
Add Final Documentations

### PR DESCRIPTION
**Pull request by eXhumer**
**THIS IS READY TO MERGE UNLESS SOMETHING NEEDS TO DO EDITED.**

Here are all the suggested changes to add the missing documentations.

Let me know if you want me to change anything.

### CODE REVIEW

**Comment by eXhumer** [comment]
Also, ignore the unverified thing. I changed my GPG key.

**Comment by tallbl0nde** [comment]
It's looking good so far! I'll probably go through after you're done and tidy a few things up (such as descriptions of elements, etc) as I've noticed some of them are a bit outdated and aren't all that helpful... that's my fault though, not yours :P

**Comment by eXhumer** [comment]
Only stuff left to document are the overlays. I will do it later tomorrow when I get the time to do so.

**Comment by eXhumer** [comment]
All documentation has been added. Let me know if you want me to change anything before it gets merged.

**Comment by eXhumer** [comment]
A preview of the generated docs can be found at https://exhumer.github.io/Aether/

**Comment by tallbl0nde** [comment]
I've had a pretty good glance over everything and I'm happy with it! Thanks so much for writing all this documentation (you have no idea how much I was dreading it), I'll make sure to credit you in the readme! :)

**Pull request merged**
