### PR TITLE
Makefile overhaul

### PR DESCRIPTION
**Pull request by eXhumer**
* Added default make target as `library`
* Added make targets to generate/clean documentations
* Added make targets to install/un-install library at $(PORTLIBS_PREFIX)
* Removed useless make variables and general cleanup

*NOTE:* The Makefile output has been drastically improves to be more human readable.

Any question about any part, feel free to let me know.

### CODE REVIEW

**Comment by eXhumer** [comment]
Hold this merge till I add some proper comments in file to make the file look better.

**Comment by eXhumer** [comment]
* To create library at directory `lib` located at root of project's folder: `make [library]`
* To install library at `$(PORTLIBS_PREFIX)`: `make install`
* To un-install library at `$(PORTLIBS_PREFIX)`: `make uninstall`
* To generate library docs: `make docs`
* To clean library docs: `make cleandocs`
* To clean build files: `make clean`

**Comment by eXhumer** [comment]
https://github.com/eXhumer/Aether/blob/7955ca6059cfdda5f8baae9586c84de0abfc5b0a/Makefile#L52

This comment needs to be fixed before this PR is merged.

**Comment by tallbl0nde** [comment]
Thanks a lot for doing this, the install rule will be useful! I've got no questions as I'm still getting my head around Makefiles :P

**Pull request merged**
