### PR TITLE
Add CI workflow for Aether

### PR DESCRIPTION
**Pull request by eXhumer**

### CODE REVIEW

**Comment by eXhumer** [comment]
I am also adding a workflow to auto generate docs and deploy latest generated on any push/pull-request. I suggest waiting till that is over before this is merged.

**Comment by eXhumer** [comment]
Done!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Docs now auto regenerate and auto updates repo's docs on any new push/pull-request. All new merges to master branch does a build test to also check if the project builds properly.

To implement updating repo docs successfully, you will have to add the following 3 secrets on your project from [here](https://github.com/tallbl0nde/Aether/settings/secrets) first before merging.

| Secret name             | Secret value                            |
|:-----------------------:|:---------------------------------------:|
| `REPO_USERNAME`         | `<your-git-username>`                   |
| `REPO_EMAIL`            | `<your-git-email>`                      |
| `PERSONAL_ACCESS_TOKEN` | `<token-with-public-repo-access-scope>` |

**Comment by eXhumer** [comment]
LMK if you have any questions, this should be ready for merge.

**Comment by eXhumer** [comment]
Closed for now. Need to fix everything first before anything gets merged.

**Comment by tallbl0nde** [comment]
No worries, I can't wait to see this working!

**Pull request closed without merging**
